import fs from 'node:fs';
import process from 'node:process';
import console from 'node:console';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { spawn, execFileSync } from 'node:child_process';
const [id, command, ...args] = process.argv.slice(2);
if (!id || !command || !/^[a-zA-Z0-9_-]+$/.test(id)) throw new Error('需要唯一命令名称及可执行程序');
const dir = path.resolve('artifacts/refactor-2026/independent-fix/main');
fs.mkdirSync(dir, { recursive: true });
const out = path.join(dir, id + '.out');
const err = path.join(dir, id + '.err');
// 全量审计会给仓库文件做快照；原始流暂存在临时目录，结束后再归档，避免日志自身改变待测树。
const staging = process.env.LINGXI_TEST_LOG_STAGING;
if (staging) fs.mkdirSync(staging, { recursive: true });
const liveOut = staging ? path.join(staging, id + '.out') : out;
const liveErr = staging ? path.join(staging, id + '.err') : err;
if (fs.existsSync(out)) throw new Error('日志已存在，使用新的命令名称');
const git = (...a) => execFileSync('git', a, { encoding: 'utf8' }).trim();
const sourceFiles = git('ls-files', '--cached', '--others', '--exclude-standard').split('\n').filter(p => /^(core|lib|server|shared|desktop|cli|scripts|tests|build|\.github)\//.test(p) || /^(package(-lock)?\.json|tsconfig[^/]*\.json|vitest\.config\.js|vite[^/]*|export-manifest\.json)$/.test(p)).filter(p => fs.existsSync(p) && fs.statSync(p).isFile()).sort();
const sourceManifest = sourceFiles.map(p => ({ path: p, sha256: crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex') }));
const manifestBytes = JSON.stringify(sourceManifest, null, 2) + '\n';
fs.writeFileSync(path.join(dir, id + '.source.json'), manifestBytes);
const sourceDigest = crypto.createHash('sha256').update(manifestBytes).digest('hex');
const record = { sourceDigest, sourceManifest: path.relative(process.cwd(), path.join(dir, id + '.source.json')), id, command: [command, ...args], cwd: process.cwd(), start: new Date().toISOString(), sha: git('rev-parse', 'HEAD'), tree: git('rev-parse', 'HEAD^{tree}'), dirty: git('status', '--porcelain'), node: process.version, platform: process.platform, arch: process.arch, os: os.release(), lockSha256: crypto.createHash('sha256').update(fs.readFileSync('package-lock.json')).digest('hex'), stdout: path.relative(process.cwd(), out), stderr: path.relative(process.cwd(), err) };
const child = spawn(command, args, { stdio: ['ignore', fs.openSync(liveOut, 'wx'), fs.openSync(liveErr, 'wx')], env: process.env });
child.on('error', error => { fs.appendFileSync(liveErr, String(error)); });
child.on('close', (code, signal) => { if (staging) { fs.copyFileSync(liveOut, out); fs.copyFileSync(liveErr, err); } record.end = new Date().toISOString(); record.exitCode = code; record.signal = signal; fs.appendFileSync(path.join(dir, 'commands.jsonl'), JSON.stringify(record) + '\n'); console.log(JSON.stringify(record)); process.exitCode = code ?? 1; });
