CREATE TABLE model_call_usage (
    model_call_id       TEXT PRIMARY KEY,
    session_id          TEXT,
    run_id              TEXT,
    attempt             TEXT,
    purpose             TEXT NOT NULL,
    origin              TEXT NOT NULL,
    parent_run_id       TEXT,
    cause_ref           TEXT,
    provider            TEXT NOT NULL,
    model               TEXT NOT NULL,
    protocol            TEXT NOT NULL,
    usage_state         TEXT NOT NULL,
    input_tokens        INTEGER,
    output_tokens       INTEGER,
    cache_read_tokens   INTEGER,
    cache_write_tokens  INTEGER,
    reasoning_tokens    INTEGER,
    missing_fields      TEXT,
    estimate_basis      TEXT,
    invalid_detail      TEXT,
    transport_attempts  INTEGER NOT NULL,
    cost_basis          TEXT,
    recorded_at_unix_ms INTEGER NOT NULL
)
