set -euo pipefail
source "$1"
bind_worktree "$2" "$4/before-a.tsv" "$5"
bind_worktree "$3" "$4/before-b.tsv" "$5"
cmp "$4/before-a.tsv" "$4/before-b.tsv"
cp "$2/source.rs" "$4/original-source"
rm "$2/source.rs" "$3/source.rs"
bind_worktree "$2" "$4/delete-a.tsv" "$5"
bind_worktree "$3" "$4/delete-b.tsv" "$5"
cmp "$4/delete-a.tsv" "$4/delete-b.tsv"
if cmp -s "$4/before-a.tsv" "$4/delete-a.tsv"; then exit 41; fi
cp "$4/original-source" "$2/source.rs"
cp "$4/original-source" "$3/source.rs"
mv "$2/source.rs" "$2/renamed.rs"
mv "$3/source.rs" "$3/renamed.rs"
bind_worktree "$2" "$4/rename-a.tsv" "$5"
bind_worktree "$3" "$4/rename-b.tsv" "$5"
cmp "$4/rename-a.tsv" "$4/rename-b.tsv"
if cmp -s "$4/before-a.tsv" "$4/rename-a.tsv"; then exit 42; fi
mv "$2/renamed.rs" "$2/source.rs"
mv "$3/renamed.rs" "$3/source.rs"
bind_worktree "$2" "$4/restored-a.tsv" "$5"
bind_worktree "$3" "$4/restored-b.tsv" "$5"
cmp "$4/before-a.tsv" "$4/restored-a.tsv"
cmp "$4/restored-a.tsv" "$4/restored-b.tsv"
