//! R05-T05: the provider-compat golden alignment suite. Every fixture in
//! `golden-compat/` is GENERATED by running the incumbent TypeScript
//! modules (docs/rust-tauri/R05/r05_t05_generate_compat_goldens.mjs — Node
//! 24 type stripping) on the same (model, payload, options) triple, so the
//! ported [`models::compat`] layer is pinned to the incumbent byte-for-byte:
//! the derivation chain (`thinkingFormat` / `reasoningProfile`), the
//! first-match dispatch decision, and the patched payload (or the verbatim
//! refusal text) all come from the TS run. Any drift breaks this suite
//! loudly.

use std::collections::BTreeMap;

use lingxi_adapters::models::compat::{self, CompatMode, CompatOptions, ModelView};
use lingxi_adapters::models::config::RouteCompatHints;
use serde_json::Value;

#[derive(serde::Deserialize)]
struct Golden {
    module: Option<String>,
    case: String,
    model: Value,
    payload: Value,
    #[serde(default)]
    options: Value,
    expected: Expected,
}

#[derive(serde::Deserialize)]
struct Expected {
    #[serde(rename = "thinkingFormat")]
    thinking_format: Option<String>,
    #[serde(rename = "reasoningProfile")]
    reasoning_profile: Option<String>,
    matched: Option<String>,
    result: Option<Value>,
    error: Option<String>,
}

/// Maps the TS model object onto the Rust view: the four route facets plus
/// the declared-hints block (the config-side half of the TS model's
/// compat/capability fields).
fn view_of(model: &Value) -> (ModelView<'static>, RouteCompatHints) {
    let text = |key: &str| {
        model
            .get(key)
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string()
    };
    let compat = model.get("compat").cloned().unwrap_or(Value::Null);
    let compat_text = |key: &str| compat.get(key).and_then(Value::as_str).map(str::to_string);
    let hints = RouteCompatHints {
        thinking_format: compat_text("thinkingFormat"),
        reasoning_profile: compat_text("reasoningProfile"),
        cache_control_format: compat_text("cacheControlFormat"),
        reasoning: model.get("reasoning").and_then(Value::as_bool),
        max_tokens: model.get("maxTokens").and_then(Value::as_u64),
        context_window: model.get("contextWindow").and_then(Value::as_u64),
        quirks: model
            .get("quirks")
            .and_then(Value::as_array)
            .map(|items| {
                items
                    .iter()
                    .filter_map(|item| item.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default(),
        thinking_level_map: model
            .get("thinkingLevelMap")
            .and_then(Value::as_object)
            .map(|map| {
                map.iter()
                    .map(|(key, value)| (key.clone(), value.as_str().map(str::to_string)))
                    .collect::<BTreeMap<String, Option<String>>>()
            }),
        // The single Rust field covers both TS reads (compat first, then the
        // top-level projection) — the generator never sets both.
        output_includes_thinking: compat
            .get("outputIncludesThinking")
            .and_then(Value::as_bool)
            .or_else(|| model.get("outputIncludesThinking").and_then(Value::as_bool)),
        video: model.get("video").and_then(Value::as_bool),
    };
    let view = ModelView {
        provider: Box::leak(text("provider").into_boxed_str()),
        model_id: Box::leak(text("id").into_boxed_str()),
        base_url: Box::leak(text("baseUrl").into_boxed_str()),
        api: Box::leak(text("api").into_boxed_str()),
        hints: None,
    };
    (view, hints)
}

fn options_of(options: &Value) -> CompatOptions {
    CompatOptions {
        mode: match options.get("mode").and_then(Value::as_str) {
            Some("utility") => CompatMode::Utility,
            _ => CompatMode::Chat,
        },
        reasoning_level: options
            .get("reasoningLevel")
            .and_then(Value::as_str)
            .map(str::to_string),
        response_schema: options.get("responseSchema").cloned(),
        reasoning_replay: options
            .get("reasoningReplay")
            .and_then(Value::as_str)
            .map(str::to_string),
        output_budget_source: options
            .get("outputBudgetSource")
            .and_then(Value::as_str)
            .map(str::to_string),
        max_tokens_source: options
            .get("maxTokensSource")
            .and_then(Value::as_str)
            .map(str::to_string),
    }
}

fn load_goldens() -> Vec<(std::path::PathBuf, Golden)> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden-compat");
    let mut files: Vec<_> = std::fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("golden dir {}: {err}", dir.display()))
        .map(|entry| entry.expect("dir entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    files.sort();
    files
        .into_iter()
        .map(|path| {
            let text = std::fs::read_to_string(&path).expect("golden readable");
            let golden: Golden = serde_json::from_str(&text)
                .unwrap_or_else(|err| panic!("{}: {err}", path.display()));
            (path, golden)
        })
        .collect()
}

#[test]
fn every_golden_aligns_with_the_incumbent_ts_run() {
    let goldens = load_goldens();
    assert!(goldens.len() >= 48, "the case table must stay registered");
    for (path, golden) in goldens {
        let context = || format!("{} ({})", path.display(), golden.case);
        let (mut view, hints) = view_of(&golden.model);
        view.hints = Some(Box::leak(Box::new(hints)));
        assert_eq!(
            compat::thinking_format(&view),
            golden.expected.thinking_format,
            "{}: thinkingFormat drift",
            context()
        );
        assert_eq!(
            compat::reasoning_profile(&view),
            golden.expected.reasoning_profile,
            "{}: reasoningProfile drift",
            context()
        );
        assert_eq!(
            compat::matched_module(&view).map(str::to_string),
            golden.expected.matched,
            "{}: dispatch drift",
            context()
        );
        assert_eq!(
            golden.module.as_deref().map(|m| m.to_string()),
            golden.expected.matched,
            "{}: fixture module/matched disagreement",
            context()
        );
        let options = options_of(&golden.options);
        let result = compat::apply(golden.payload.clone(), &view, &options);
        match (&golden.expected.result, &golden.expected.error) {
            (Some(expected), None) => {
                let patched = result.unwrap_or_else(|err| {
                    panic!(
                        "{}: port refused where the incumbent patched: {err}",
                        context()
                    )
                });
                assert_eq!(&patched, expected, "{}: patched payload drift", context());
            }
            (None, Some(expected_error)) => {
                let error = match result {
                    Err(error) => error,
                    Ok(patched) => panic!(
                        "{}: port patched where the incumbent refused: {patched}",
                        context()
                    ),
                };
                assert_eq!(
                    &error.message,
                    expected_error,
                    "{}: refusal text drift",
                    context()
                );
                assert_eq!(
                    error.code,
                    lingxi_protocol::ErrorCode::InvalidMessage,
                    "{}: the refusal class is pinned",
                    context()
                );
                assert!(
                    !error.retryable,
                    "{}: a compat refusal never retries",
                    context()
                );
            }
            other => panic!("{}: malformed expected block {other:?}", context()),
        }
    }
}
